name: pruebakidsandclouds
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Estado
  flutter_riverpod: ^2.5.3
  json_annotation: ^4.9.0

  # Peticiones HTTP y serialización
  dio: ^5.7.0
  retrofit: ^4.4.2
  
  # Navegación
  go_router: ^14.6.2
  
  # UI
  google_fonts: ^6.2.1
  intl: ^0.19.0

  
  # Local storage y seguridad
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.6
  retrofit_generator: ^9.2.0
  mockito: ^5.4.0
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.14.1 

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/data/
    - assets/img/
    - assets/icons/

flutter_intl:
  enabled: true

flutter_launcher_icons:
  image_path: "assets/img/logo.png" 
  android: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21


flutter_native_splash:
  image:  "assets/img/logo.png" 
  color: "#FFFFFF"
  android_12:
    image: assets/img/logo.png
    color: "#FFFFFF"
  ios: true
  android: true
  web: true